name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false 

      - name: Install and Build 🔧
        run: |
          npm install
          npm react-scripts build
        env:
          REACT_APP_APIKey: ${{ secrets.REACT_APP_APIKey }}
          REACT_APP_APISecret: ${{ secrets.REACT_APP_APISecret }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
